### ISSUE TITLE
Invisible clock

### ISSUE THREAD

**Issue by kityan** [svr93/custom-clock#28]
Trying with simple React boilerplate: https://github.com/kityan/react-custom-clock

**Chrome 71 / Windows 7**
custom-clock element appears in DOM without attr `size="100px"` and invisible (renders to block with size 0x16 (according to DOM inspector))
If I set `size="100px"` manually via DOM inspector the element becomes visible.
If I change to `size="100"` in code it appears with `size="100"` but with no effect.

**Firefox 58 / Windows 7**
customElements not defined

P.S. 

I see in my transpiled code this line: 
```js
_react2.default.createElement('custom-clock', { size: '100px', 'stroke-color': '#536dfe' })
```
It means that custom-clock is treated as an element (not a React component) by React and it's OK.

**Comment by svr93** [comment]
@kityan Thanks for trying the component with React!

1) Seems it's necessary to use some default size as for `stroke-color` attribute.
2) With respect to `size="100"`: documentation describes acceptable value as valid CSS value:
```
CSS.supports('width', '100') // false
CSS.supports('width', '100px') // true
```
Will fallback to pixel units be an intuitive behavior? I think that warning in the console for all unacceptable values will be better.

3) For old Firefox, please try
```
dom.webcomponents.enabled -> true
dom.webcomponents.customelements.enabled -> true
```
Unfortunately, I have no plans for fallback behavior for browsers that not support Web Components; the first step was to launch the project in modern, evergreen browsers.

**Comment by kityan** [comment]
@svr93 Sure, `100px` is not a valid CSS `width` value, but one can expect it unitless because of it is an attribute value. But, anyway, I'm just curious why is `100` passed to DOM and `100px` is not?
Do you have the same behaviour with my repo?

**Comment by svr93** [comment]
@kityan PR is ready: https://github.com/svr93/custom-clock/pull/29

Under the hood: it checks value for validity with `CSS.supports` and uses warnings with tips
I'll try the component with your repo too!

**Comment by svr93** [comment]
@kityan Is there enough error output without fallback behavior?

**Comment by kityan** [comment]
@svr93 Yep, I think it's enough but the real issue is about ignoring `100px` in my example.

**Comment by svr93** [comment]
@kityan Had time to test the component inside your project) Strange behavior but works after renaming attribute to `size-a` (for example)

**Comment by svr93** [comment]
@kityan I have a plan to publish `custom-clock` v2 with `dial-size` instead of `size` attribute.
Seems React doesn't support some restricted names for Web Components:
https://reactjs.org/docs/dom-elements.html
```Some of the DOM attributes supported by React include:...```

**Comment by kityan** [comment]
@svr Yeah, another attr (`stroke-color`) is OK too...
I think React tries to validate attribute `size`. And it is invalid as `100px` because HTML defines `size` as unitless for Input and Select (https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes)
Also this explains why `size="100"` appears in DOM but `size="100px"` – doesn't.

**Comment by kityan** [comment]
@svr93 Usage of `data-*` attributes should be a safe solution, but is less convinient and pretty.

**Comment by svr93** [comment]
@kityan Prepared the branch https://github.com/svr93/custom-clock/tree/v2

**Comment by svr93** [comment]
@kityan Version 2 is available on npm) Feel free to test it (I have already tested the component with your project, it's OK)
Gimme a sign if I can close the issue ;)

**Comment by kityan** [comment]
Here is the sign.
